// <auto-generated />
namespace Teachersteams.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AssignmentResultTable_AsigneeTecher_AddForeignKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssignmentResultTable_AsigneeTecher_AddForeignKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201605032227378_AssignmentResultTable_AsigneeTecher_AddForeignKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
