// <auto-generated />
namespace Teachersteams.Migrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentAndTeacherTablesAddForeignKeyToGroupTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentAndTeacherTablesAddForeignKeyToGroupTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201604202215036_StudentAndTeacherTablesAddForeignKeyToGroupTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
