//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teachersteams.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teachersteams.Presentation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTabTitle {
            get {
                return ResourceManager.GetString("AboutTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllGroupsFilterText {
            get {
                return ResourceManager.GetString("AllGroupsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string AssistantGroupsFilterText {
            get {
                return ResourceManager.GetString("AssistantGroupsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string BoardTabTitle {
            get {
                return ResourceManager.GetString("BoardTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonLabel {
            get {
                return ResourceManager.GetString("CloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButtonLabel {
            get {
                return ResourceManager.GetString("CreateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroupButtonLabel {
            get {
                return ResourceManager.GetString("CreateGroupButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new group.
        /// </summary>
        public static string CreateGroupDialogTitle {
            get {
                return ResourceManager.GetString("CreateGroupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in this field. It cannot be empty..
        /// </summary>
        public static string FieldIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("FieldIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string GroupCreateDateLabel {
            get {
                return ResourceManager.GetString("GroupCreateDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description is too long.
        /// </summary>
        public static string GroupDescriptionIsLongValidationMessage {
            get {
                return ResourceManager.GetString("GroupDescriptionIsLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GroupDescriptionLabel {
            get {
                return ResourceManager.GetString("GroupDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can describe groupe in more details.
        /// </summary>
        public static string GroupDescriptionPlaceholderMessage {
            get {
                return ResourceManager.GetString("GroupDescriptionPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string GroupInfoTabTitle {
            get {
                return ResourceManager.GetString("GroupInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string GroupOwnerLabel {
            get {
                return ResourceManager.GetString("GroupOwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsTabTitle {
            get {
                return ResourceManager.GetString("GroupsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string GroupStudentsTabTitle {
            get {
                return ResourceManager.GetString("GroupStudentsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string GroupTasksTabTitle {
            get {
                return ResourceManager.GetString("GroupTasksTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string GroupTeachersTabTitle {
            get {
                return ResourceManager.GetString("GroupTeachersTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group title is too long.
        /// </summary>
        public static string GroupTitleIsLongValidationMessage {
            get {
                return ResourceManager.GetString("GroupTitleIsLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group title is required.
        /// </summary>
        public static string GroupTitleIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("GroupTitleIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GroupTitleLabel {
            get {
                return ResourceManager.GetString("GroupTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a group title.
        /// </summary>
        public static string GroupTitlePlaceholderMessage {
            get {
                return ResourceManager.GetString("GroupTitlePlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string HeaderGroups {
            get {
                return ResourceManager.GetString("HeaderGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string InternalErrorTitle {
            get {
                return ResourceManager.GetString("InternalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string InviteButtonLabel {
            get {
                return ResourceManager.GetString("InviteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite student.
        /// </summary>
        public static string InviteStudentDilaogTitle {
            get {
                return ResourceManager.GetString("InviteStudentDilaogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite teacher.
        /// </summary>
        public static string InviteTeacherDilaogTitle {
            get {
                return ResourceManager.GetString("InviteTeacherDilaogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not study in any group..
        /// </summary>
        public static string NoGroupsDescriptionForStudent {
            get {
                return ResourceManager.GetString("NoGroupsDescriptionForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not groups that satisfied the selected filter..
        /// </summary>
        public static string NoGroupsDescriptionForTeacher {
            get {
                return ResourceManager.GetString("NoGroupsDescriptionForTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups.
        /// </summary>
        public static string NoGroupsMessage {
            get {
                return ResourceManager.GetString("NoGroupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resoults.
        /// </summary>
        public static string NoResultsMessage {
            get {
                return ResourceManager.GetString("NoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Requested the page that is no longer There..
        /// </summary>
        public static string NotFoundDescription {
            get {
                return ResourceManager.GetString("NotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationsTabTitle {
            get {
                return ResourceManager.GetString("NotificationsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohh.
        /// </summary>
        public static string Ohh {
            get {
                return ResourceManager.GetString("Ohh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string OhhFirstPart {
            get {
                return ResourceManager.GetString("OhhFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh......
        /// </summary>
        public static string OhhSecondPart {
            get {
                return ResourceManager.GetString("OhhSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own.
        /// </summary>
        public static string OwnGroupsFilterText {
            get {
                return ResourceManager.GetString("OwnGroupsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeachersTeams.
        /// </summary>
        public static string SiteHeaderText {
            get {
                return ResourceManager.GetString("SiteHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachersteams.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string SorryString {
            get {
                return ResourceManager.GetString("SorryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where you are a student.
        /// </summary>
        public static string StudentsGroupsSubHeader {
            get {
                return ResourceManager.GetString("StudentsGroupsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string StudentSwitchLabel {
            get {
                return ResourceManager.GetString("StudentSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type user name here.
        /// </summary>
        public static string TeacherNamePlaseholderMessage {
            get {
                return ResourceManager.GetString("TeacherNamePlaseholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string TeachersGridActionsColumnName {
            get {
                return ResourceManager.GetString("TeachersGridActionsColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string TeachersGridFullNameColumnName {
            get {
                return ResourceManager.GetString("TeachersGridFullNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string TeachersGridPhotoColumnName {
            get {
                return ResourceManager.GetString("TeachersGridPhotoColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uid.
        /// </summary>
        public static string TeachersGridUidColumnName {
            get {
                return ResourceManager.GetString("TeachersGridUidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where you are a teacher.
        /// </summary>
        public static string TeachersGroupsSubHeader {
            get {
                return ResourceManager.GetString("TeachersGroupsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string TeacherSwitchLabel {
            get {
                return ResourceManager.GetString("TeacherSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS! Unexpected Error Occurred!.
        /// </summary>
        public static string UnexpectedErrorDescription {
            get {
                return ResourceManager.GetString("UnexpectedErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
    }
}
