//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teachersteams.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teachersteams.Presentation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTabTitle {
            get {
                return ResourceManager.GetString("AboutTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptButtonLabel {
            get {
                return ResourceManager.GetString("AcceptButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close without saving your changes?.
        /// </summary>
        public static string AddAssignmentDialogCloseConfirmationMessage {
            get {
                return ResourceManager.GetString("AddAssignmentDialogCloseConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllGroupsFilterText {
            get {
                return ResourceManager.GetString("AllGroupsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string AllUsersUserSearchTypeName {
            get {
                return ResourceManager.GetString("AllUsersUserSearchTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment has been completed successfully..
        /// </summary>
        public static string AssignmentCompletedSuccessMessage {
            get {
                return ResourceManager.GetString("AssignmentCompletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new assignment has been created..
        /// </summary>
        public static string AssignmentCreatedMessage {
            get {
                return ResourceManager.GetString("AssignmentCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment description is too long..
        /// </summary>
        public static string AssignmentDescriptionIsLongValidationMessage {
            get {
                return ResourceManager.GetString("AssignmentDescriptionIsLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can describe assignment in more details.
        /// </summary>
        public static string AssignmentDescriptionPlaceholderMessage {
            get {
                return ResourceManager.GetString("AssignmentDescriptionPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment expiration date is invalid..
        /// </summary>
        public static string AssignmentExpirationDateIsInvalidValidationMessage {
            get {
                return ResourceManager.GetString("AssignmentExpirationDateIsInvalidValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment expiration date is required..
        /// </summary>
        public static string AssignmentExpirationDateIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("AssignmentExpirationDateIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Results.
        /// </summary>
        public static string AssignmentResultsDialogTitle {
            get {
                return ResourceManager.GetString("AssignmentResultsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string AssignmentResultsGridAssigneeColumnName {
            get {
                return ResourceManager.GetString("AssignmentResultsGridAssigneeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string AssignmentResultsGridCheckedColumnName {
            get {
                return ResourceManager.GetString("AssignmentResultsGridCheckedColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string AssignmentResultsGridFinishedColumnName {
            get {
                return ResourceManager.GetString("AssignmentResultsGridFinishedColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string AssignmentResultsGridGradeColumnName {
            get {
                return ResourceManager.GetString("AssignmentResultsGridGradeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string AssignmentResultsGridPhotoColumnName {
            get {
                return ResourceManager.GetString("AssignmentResultsGridPhotoColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string AssignmentResultsGridStudentColumnName {
            get {
                return ResourceManager.GetString("AssignmentResultsGridStudentColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string AssignmentsGridExpirationColumnName {
            get {
                return ResourceManager.GetString("AssignmentsGridExpirationColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AssignmentsGridStatusColumnName {
            get {
                return ResourceManager.GetString("AssignmentsGridStatusColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AssignmentsGridTitleColumnName {
            get {
                return ResourceManager.GetString("AssignmentsGridTitleColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string AssignmentStatusEnumActive {
            get {
                return ResourceManager.GetString("AssignmentStatusEnumActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string AssignmentStatusEnumDraft {
            get {
                return ResourceManager.GetString("AssignmentStatusEnumDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string AssignmentStatusEnumExpired {
            get {
                return ResourceManager.GetString("AssignmentStatusEnumExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment title is too long..
        /// </summary>
        public static string AssignmentTitleIsLongValidationMessage {
            get {
                return ResourceManager.GetString("AssignmentTitleIsLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment title is required..
        /// </summary>
        public static string AssignmentTitleIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("AssignmentTitleIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a assignment title.
        /// </summary>
        public static string AssignmentTitlePlaceholderMessage {
            get {
                return ResourceManager.GetString("AssignmentTitlePlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to assignm to myself this assignment result for checking..
        /// </summary>
        public static string AssignToMeAssignmnetResultActionTooltip {
            get {
                return ResourceManager.GetString("AssignToMeAssignmnetResultActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string AssistantGroupsFilterText {
            get {
                return ResourceManager.GetString("AssistantGroupsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string BoardTabTitle {
            get {
                return ResourceManager.GetString("BoardTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButtonLabel {
            get {
                return ResourceManager.GetString("BrowseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonLabel {
            get {
                return ResourceManager.GetString("CloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select your answers and to send it for checking..
        /// </summary>
        public static string CompleteAssignmentActionTooltip {
            get {
                return ResourceManager.GetString("CompleteAssignmentActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete assignment .
        /// </summary>
        public static string CompleteAssignmentDialogTitle {
            get {
                return ResourceManager.GetString("CompleteAssignmentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string CompleteButtonLabel {
            get {
                return ResourceManager.GetString("CompleteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create assignment.
        /// </summary>
        public static string CreateAssignmentButtonLabel {
            get {
                return ResourceManager.GetString("CreateAssignmentButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Assignment.
        /// </summary>
        public static string CreateAssignmentDialogTitle {
            get {
                return ResourceManager.GetString("CreateAssignmentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButtonLabel {
            get {
                return ResourceManager.GetString("CreateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroupButtonLabel {
            get {
                return ResourceManager.GetString("CreateGroupButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new group.
        /// </summary>
        public static string CreateGroupDialogTitle {
            get {
                return ResourceManager.GetString("CreateGroupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string DeclineButtonLabel {
            get {
                return ResourceManager.GetString("DeclineButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this user from list of students..
        /// </summary>
        public static string DeleteStudentTooltipMessage {
            get {
                return ResourceManager.GetString("DeleteStudentTooltipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this user from list of teachers..
        /// </summary>
        public static string DeleteTeacherTooltipMessage {
            get {
                return ResourceManager.GetString("DeleteTeacherTooltipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove.
        /// </summary>
        public static string DeleteUserConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteUserConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string DeleteUserDialogTitle {
            get {
                return ResourceManager.GetString("DeleteUserDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to download assignment..
        /// </summary>
        public static string DownloadAssignmentActionTooltip {
            get {
                return ResourceManager.GetString("DownloadAssignmentActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to download assignment result..
        /// </summary>
        public static string DownloadAssignmentResultActionTooltip {
            get {
                return ResourceManager.GetString("DownloadAssignmentResultActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permissions.
        /// </summary>
        public static string EditPermissionsDialogTitle {
            get {
                return ResourceManager.GetString("EditPermissionsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permissions of this user..
        /// </summary>
        public static string EditPermissionsTooltipMessage {
            get {
                return ResourceManager.GetString("EditPermissionsTooltipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in this field. It cannot be empty..
        /// </summary>
        public static string FieldIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("FieldIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach a file..
        /// </summary>
        public static string FileIsNotAttachedMessage {
            get {
                return ResourceManager.GetString("FileIsNotAttachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string GroupAssignmentsTabTitle {
            get {
                return ResourceManager.GetString("GroupAssignmentsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string GroupCreateDateLabel {
            get {
                return ResourceManager.GetString("GroupCreateDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description is too long.
        /// </summary>
        public static string GroupDescriptionIsLongValidationMessage {
            get {
                return ResourceManager.GetString("GroupDescriptionIsLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GroupDescriptionLabel {
            get {
                return ResourceManager.GetString("GroupDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can describe groupe in more details.
        /// </summary>
        public static string GroupDescriptionPlaceholderMessage {
            get {
                return ResourceManager.GetString("GroupDescriptionPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string GroupInfoTabTitle {
            get {
                return ResourceManager.GetString("GroupInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string GroupOwnerLabel {
            get {
                return ResourceManager.GetString("GroupOwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsTabTitle {
            get {
                return ResourceManager.GetString("GroupsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string GroupStudentsTabTitle {
            get {
                return ResourceManager.GetString("GroupStudentsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string GroupTeachersTabTitle {
            get {
                return ResourceManager.GetString("GroupTeachersTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group title is too long.
        /// </summary>
        public static string GroupTitleIsLongValidationMessage {
            get {
                return ResourceManager.GetString("GroupTitleIsLongValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group title is required.
        /// </summary>
        public static string GroupTitleIsRequiredValidationMessage {
            get {
                return ResourceManager.GetString("GroupTitleIsRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GroupTitleLabel {
            get {
                return ResourceManager.GetString("GroupTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a group title.
        /// </summary>
        public static string GroupTitlePlaceholderMessage {
            get {
                return ResourceManager.GetString("GroupTitlePlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string HeaderGroups {
            get {
                return ResourceManager.GetString("HeaderGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string InternalErrorTitle {
            get {
                return ResourceManager.GetString("InternalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to study in group.
        /// </summary>
        public static string InvitationMessageForStudent {
            get {
                return ResourceManager.GetString("InvitationMessageForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to teach in group.
        /// </summary>
        public static string InvitationMessageForTeacher {
            get {
                return ResourceManager.GetString("InvitationMessageForTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string InviteButtonLabel {
            get {
                return ResourceManager.GetString("InviteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are invited..
        /// </summary>
        public static string InvitedMessage {
            get {
                return ResourceManager.GetString("InvitedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite student.
        /// </summary>
        public static string InviteStudentDilaogTitle {
            get {
                return ResourceManager.GetString("InviteStudentDilaogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite teacher.
        /// </summary>
        public static string InviteTeacherDilaogTitle {
            get {
                return ResourceManager.GetString("InviteTeacherDilaogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButtonLabel {
            get {
                return ResourceManager.GetString("NoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not study in any group..
        /// </summary>
        public static string NoGroupsDescriptionForStudent {
            get {
                return ResourceManager.GetString("NoGroupsDescriptionForStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not groups that satisfied the selected filter..
        /// </summary>
        public static string NoGroupsDescriptionForTeacher {
            get {
                return ResourceManager.GetString("NoGroupsDescriptionForTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups.
        /// </summary>
        public static string NoGroupsMessage {
            get {
                return ResourceManager.GetString("NoGroupsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no new notifications yet..
        /// </summary>
        public static string NoNotificationsMessage {
            get {
                return ResourceManager.GetString("NoNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resoults.
        /// </summary>
        public static string NoResultsMessage {
            get {
                return ResourceManager.GetString("NoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Requested the page that is no longer There..
        /// </summary>
        public static string NotFoundDescription {
            get {
                return ResourceManager.GetString("NotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationsTabTitle {
            get {
                return ResourceManager.GetString("NotificationsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohh.
        /// </summary>
        public static string Ohh {
            get {
                return ResourceManager.GetString("Ohh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string OhhFirstPart {
            get {
                return ResourceManager.GetString("OhhFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh......
        /// </summary>
        public static string OhhSecondPart {
            get {
                return ResourceManager.GetString("OhhSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Friends.
        /// </summary>
        public static string OnlyFriendsUserSearchTypeName {
            get {
                return ResourceManager.GetString("OnlyFriendsUserSearchTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own.
        /// </summary>
        public static string OwnGroupsFilterText {
            get {
                return ResourceManager.GetString("OwnGroupsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to rate assignment result..
        /// </summary>
        public static string RateAssignmnetResultActionTooltip {
            get {
                return ResourceManager.GetString("RateAssignmnetResultActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeachersTeams.
        /// </summary>
        public static string SiteHeaderText {
            get {
                return ResourceManager.GetString("SiteHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachersteams.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string SorryString {
            get {
                return ResourceManager.GetString("SorryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept to study in this group?.
        /// </summary>
        public static string StudentConfirmationMessage {
            get {
                return ResourceManager.GetString("StudentConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where you are a student.
        /// </summary>
        public static string StudentsGroupsSubHeader {
            get {
                return ResourceManager.GetString("StudentsGroupsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string StudentSwitchLabel {
            get {
                return ResourceManager.GetString("StudentSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept to teach in this group?.
        /// </summary>
        public static string TeacherConfirmationMessage {
            get {
                return ResourceManager.GetString("TeacherConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type user name here.
        /// </summary>
        public static string TeacherNamePlaseholderMessage {
            get {
                return ResourceManager.GetString("TeacherNamePlaseholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string TeachersGridActionsColumnName {
            get {
                return ResourceManager.GetString("TeachersGridActionsColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string TeachersGridFullNameColumnName {
            get {
                return ResourceManager.GetString("TeachersGridFullNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string TeachersGridPhotoColumnName {
            get {
                return ResourceManager.GetString("TeachersGridPhotoColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uid.
        /// </summary>
        public static string TeachersGridUidColumnName {
            get {
                return ResourceManager.GetString("TeachersGridUidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where you are a teacher.
        /// </summary>
        public static string TeachersGroupsSubHeader {
            get {
                return ResourceManager.GetString("TeachersGroupsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string TeacherSwitchLabel {
            get {
                return ResourceManager.GetString("TeacherSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS! Unexpected Error Occurred!.
        /// </summary>
        public static string UnexpectedErrorDescription {
            get {
                return ResourceManager.GetString("UnexpectedErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading to cloud....
        /// </summary>
        public static string UploadingToCloudMessage {
            get {
                return ResourceManager.GetString("UploadingToCloudMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see your results..
        /// </summary>
        public static string ViewAssignmentResultActionTooltip {
            get {
                return ResourceManager.GetString("ViewAssignmentResultActionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Grades.
        /// </summary>
        public static string ViewGradesDialogTitle {
            get {
                return ResourceManager.GetString("ViewGradesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View grades of this student..
        /// </summary>
        public static string ViewGradesTooltipMessage {
            get {
                return ResourceManager.GetString("ViewGradesTooltipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButtonLabel {
            get {
                return ResourceManager.GetString("YesButtonLabel", resourceCulture);
            }
        }
    }
}
